# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eresapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
