# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 10:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eresapp', '0007_auto_20180801_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('docs', models.FileField(null=True, upload_to='Documents/eres/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=django.contrib.auth.models.User)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('prices', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('docs', models.FileField(null=True, upload_to='Documents/research/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name=django.contrib.auth.models.User)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_images',
            field=models.FileField(null=True, upload_to='photos/blog/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
